### ISSUE TITLE
Segmentation fault when blueprint contains only metadata

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/snowcrash#205]
```
FORMAT: 1A : SOJ
```
### Actual

Segmentation fault.
### Expected

``` yaml
_version: 2.0
metadata:
- name: "FORMAT"
  value: "1A : SOJ"
name:
description:
resourceGroups:
```
