### ISSUE TITLE
Missing link while using reference-style links

### ISSUE THREAD

**Issue by zdne** [apiaryio/snowcrash#213]
### Given

```
# API
This is [an example][id]

[id]: http://a.com
```
### Actual

``` yaml
_version: 2.0
metadata:
name: "API"
description: "This is [an example][id]\n\n["
resourceGroups:
```
