### ISSUE TITLE
MSON - array|enum samples wrong parsed

### ISSUE THREAD

**Issue by klokane** [apiaryio/snowcrash#327]
according to MSON spec:
https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#44-sample

```
- list: 3, 4 (enum, sample)
```

Is equivalent to:

```
- list: *3, 4* (enum)
```

but if you sent it to snowcrash, following blueprint:

```
# <API name>
<API description>

# Data Structures

## User (object)
- list1: 3, 4 (enum, sample)
- list2: *3, 4* (enum)
```

Result is following:

```
_version: "3.0"
metadata: []
name: "<API name>"
description: "<API description>\n\n"
element: "category"
resourceGroups: []
content:
  -
    element: "category"
    content:
      -
        element: "dataStructure"
        name:
          literal: "User"
          variable: false
        typeDefinition:
          typeSpecification:
            name: "object"
            nestedTypes: []
          attributes: []
        sections:
          -
            class: "memberType"
            content:
              -
                content:
                  name:
                    literal: "list1"
                  description: ""
                  valueDefinition:
                    values:
                      -
                        literal: "3"
                        variable: false
                      -
                        literal: "4"
                        variable: false
                    typeDefinition:
                      typeSpecification:
                        name: "enum"
                        nestedTypes: []
                      attributes:
                        - "sample"
                  sections: []
                class: "property"
              -
               content:
                  name:
                    literal: "list2"
                  description: ""
                  valueDefinition:
                    values:
                      -
                        literal: "*3"
                        variable: false
                      -
                        literal: "4*"
                        variable: false
                    typeDefinition:
                      typeSpecification:
                        name: "enum"
                        nestedTypes: []
                      attributes: []
                  sections: []
                class: "property"
```

`list1` has `sample` atribute, `list2` has no. And `valueDefinition` are in both cases different too
