### ISSUE TITLE
Parentheses in parameter description breaks parmeter traits

### ISSUE THREAD

**Issue by zdne** [apiaryio/snowcrash#49]
Blueprint:

```
# GET /{id}
+ Parameters
  + id (string) ... lorem (ipsum)

+ response 204
```

Result:

``` yaml
- name:
  description:
  method: GET
  parameters:
    id:
      description:
      type: string) ... lorem (ipsum
      required: true
      default:
      example:
      values:
```
